CREATE TABLE "User" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    studentId TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    avatar TEXT,
    bio TEXT,
    role TEXT NOT NULL DEFAULT 'user',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Follow" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    followerId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    followingId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(followerId, followingId)
);
CREATE TABLE "Course" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    description TEXT
);
CREATE TABLE "Question" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    images TEXT,
    courseId INTEGER NOT NULL REFERENCES "Course"(id) ON DELETE CASCADE,
    userId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'active',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Answer" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    questionId INTEGER NOT NULL REFERENCES "Question"(id) ON DELETE CASCADE,
    userId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    isAdopted BOOLEAN NOT NULL DEFAULT 0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Comment" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    questionId INTEGER REFERENCES "Question"(id) ON DELETE CASCADE,
    answerId INTEGER REFERENCES "Answer"(id) ON DELETE CASCADE,
    userId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Resource" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT,
    filePath TEXT NOT NULL,
    fileName TEXT NOT NULL,
    fileSize INTEGER NOT NULL,
    fileType TEXT NOT NULL,
    courseId INTEGER NOT NULL REFERENCES "Course"(id) ON DELETE CASCADE,
    userId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    downloadCount INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Like" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    questionId INTEGER REFERENCES "Question"(id) ON DELETE CASCADE,
    answerId INTEGER REFERENCES "Answer"(id) ON DELETE CASCADE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(userId, questionId),
    UNIQUE(userId, answerId)
);
CREATE TABLE "Favorite" (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
    questionId INTEGER REFERENCES "Question"(id) ON DELETE CASCADE,
    resourceId INTEGER REFERENCES "Resource"(id) ON DELETE CASCADE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(userId, questionId),
    UNIQUE(userId, resourceId)
);
CREATE TABLE "_prisma_migrations" (
    id TEXT PRIMARY KEY,
    checksum TEXT NOT NULL,
    finished_at DATETIME,
    migration_name TEXT NOT NULL,
    logs TEXT,
    rolled_back_at DATETIME,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_steps_count INTEGER NOT NULL DEFAULT 0
);
INSERT INTO "_prisma_migrations" VALUES ('init', 'manual', datetime('now'), 'init', NULL, NULL, datetime('now'), 1);